#Definition Namespace für alle Ressourcen
apiVersion: v1
kind: Namespace
metadata:
  name: JSVAR_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucvisualization
  namespace: JSVAR_NAMESPACE
  labels:
    app: ucvisualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucvisualization
  template:
    metadata:
      labels:
        app: ucvisualization
    spec:
      containers:
      - name: ucvisualization
        image: JSVAR_DOCKERIMAGE
        env:
        - name: UC_CUSTOMER
          value: JSVAR_UC_CUSTOMER
        - name: UC_DBNAME
          value: JSVAR_UC_DBNAME
        - name: UC_DBUSER
          value: JSVAR_UC_DBUSER
        - name: UC_DBDB
          value: JSVAR_UC_DBDB
        - name: UC_DBPSWD
          value: JSVAR_UC_DBPSWD
        - name: UC_DOMAIN
          value: JSVAR_UC_DOMAIN
---
apiVersion: v1
kind: Service
metadata:
  name: ucvisualization-service
  namespace: JSVAR_NAMESPACE
spec:
  type: NodePort
  selector:
    app: ucvisualization
  ports:
  - protocol: TCP
    port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ucvisualization-ingress
  namespace: JSVAR_NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /JSVAR_NAMESPACE/ucvisualization/(.*)
          backend:
            serviceName: ucvisualization-service
            servicePort: 80