apiVersion: apps/v1
kind: Deployment
metadata:
  name: ucvisualization
  labels:
    app: ucvisualization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ucvisualization
  template:
    metadata:
      labels:
        app: ucvisualization
    spec:
      containers:
      - name: ucvisualization
        image: JSVAR_DOCKERIMAGE
---
apiVersion: v1
kind: Service
metadata:
  name: ucvisualization-service
spec:
  type: NodePort
  selector:
    app: ucvisualization
  ports:
  - protocol: TCP
    port: 80
---
#Definition Reverse-Proxy für einen Service
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ucvisualization-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
        - path: /ucvisualization/(.*)
          backend:
            serviceName: ucvisualization-service
            servicePort: 80